on:
  push:
    branches:
      - lecture-10
      - main
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: install dependencies
        run: npm ci
      - run: npm test